export default {
    CREATE_PLAYLIST: "CREATE_PLAYLIST",
    REMOVE_PLAYLIST: "REMOVE_PLAYLIST",
    ADD_SONG: "ADD_SONG",
    REMOVE_SONG: "REMOVE_SONG",
    OPEN_NEW_PLAYLIST: "OPEN_NEW_PLAYLIST",
    CLOSE_NEW_PLAYLIST: "CLOSE_NEW_PLAYLIST",
    OPEN_LIST_OF_PLAYLIST: "OPEN_LIST_OF_PLAYLIST",
    CLOSE_LIST_OF_PLAYLIST: "CLOSE_LIST_OF_PLAYLIST",
}